### ISSUE TITLE
trajectory-training

### ISSUE THREAD

**Issue by AboudyKreidieh** [zhefu0604/DDPGfD#3]
## Tasks
- [ ] setup Nathan's simulator as a gym environment
- [ ] reformat the way way trajectories are added to the training procedure
- [ ] verify the reward in the demo data is not relevant
- [ ] add trajectories from Amaury's controller
- [ ] add trajectories from Arwa's controller
